### ISSUE TITLE
Persistence storage for the data in the host

### ISSUE THREAD

**Issue by maestrofx** [flaccid/docker-s3-backed-ftp-server#1]
Hi @flaccid ,
Trickily, the data stored in S3 isn't mounted in the host's side (only available in that container). I've tried to mount the `/srv` ( `-v /srv/S3FOLDER:/srv`), but no change. Any suggestion?

Thank you.

**Comment by flaccid** [comment]
Not quite sure. What is your use case for the host getting the files? You could try another container with `--volumes-from`. No time for me to play atm 😑

**Comment by maestrofx** [comment]
Bingo!
Just add `:shared` param in `-v /srv:/srv:shared`, it works!

Thanks

**Comment by flaccid** [comment]
Makes sense!
